[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[character]
success_symbol = "[ï”ï”ó°…‚](bold green)"
error_symbol = "[ï”ï”ó°…‚](bold red)"
# success_symbol = "[Î»](bold green)"
# error_symbol = "[Î»](bold red)"

